import { FAL_IMAGE_MODELS, FAL_VIDEO_MODELS, falModelSummary } from '../../../shared/fal-models';
import type { AgentToolSchema } from '../tool-schema';
import { MINIMAX_LANGUAGE_BOOSTS } from '../../../shared/media-provider-params';

/** Anthropic schema for generating class tools. Just push into this array (it will automatically enter the model's visible tool list). */
export const GENERATE_TOOL_SCHEMAS: AgentToolSchema[] = [
  {
    name: 'submit_image',
    description: 'Tạo một hoặc nhiều ảnh AI (catalog Fal, gpt-image-2, nano-banana, MiniMax image-01, WaveSpeed, BytePlus Seedream hoặc xAI Grok Imagine), lưu vào kho media của dự án và tùy chọn đề xuất thêm vào dòng thời gian hiện tại. Chỉ gọi khi người dùng yêu cầu tạo ảnh rõ ràng.',
    input_schema: {
      type: 'object',
      properties: {
        model: { type: 'string', enum: ['gpt-image-2', 'nano-banana', 'image-01', 'wavespeed', 'byteplus', 'grok-imagine', 'fal'], description: 'gpt-image-2 là mặc định; nano-banana phù hợp khi dùng nhiều ảnh tham chiếu; image-01 là MiniMax (tối đa 9 kết quả; một tham chiếu chủ thể khi đã cấu hình R2); wavespeed là WaveSpeed AI (mô hình ảnh tổng quát nhanh, không có tham chiếu); byteplus là BytePlus ModelArk Seedream (chưa hỗ trợ tham chiếu); grok-imagine là xAI Grok Imagine (chỉ text-to-image, không tham chiếu, tối đa 4 kết quả, 1K/2K).' },
        falModel: { type: 'string', enum: FAL_IMAGE_MODELS.map((model) => model.id), description: `Với model=fal, chọn một mô hình ảnh Fal trong catalog; bỏ qua sẽ dùng mặc định Fal đã lưu. ${FAL_IMAGE_MODELS.map((model) => `${model.id}: ${falModelSummary(model)}`).join('; ')}. Giới hạn riêng của từng mô hình được kiểm tra trước khi gửi.` },
        prompt: { type: 'string', description: 'Mô tả chi tiết ảnh cần tạo.' },
        name: { type: 'string', description: 'Tên mô tả ngắn của tư liệu hiển thị trong kho media.' },
        addToTimeline: { type: 'boolean', description: 'Mặc định là true. Đặt false khi người dùng muốn chỉ giữ kết quả trong kho media/thư viện hoặc yêu cầu không sửa dòng thời gian.' },
        aspectRatio: { type: 'string', enum: [...new Set(['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3', '4:5', '5:4', '21:9', ...FAL_IMAGE_MODELS.flatMap((model) => model.constraints.aspectRatios)])], description: 'Provider gốc mặc định 16:9; Fal dùng mặc định của mô hình được chọn. Tỷ lệ riêng của Fal cần mô hình hỗ trợ. Không gửi width/height cùng aspectRatio.' },
        imageSize: { type: 'string', enum: [...new Set(['512px', '1K', '2K', '4K', ...FAL_IMAGE_MODELS.flatMap((model) => model.constraints.resolutions)])], description: 'Provider gốc mặc định 1K; Fal dùng mặc định của mô hình và kiểm tra kích thước được hỗ trợ. Với Fal, 512px là bí danh của 0.5K. Chỉ dùng 2K/4K khi được yêu cầu rõ ràng. Bị bỏ qua khi đặt width/height tùy chỉnh.' },
        width: { type: 'integer', minimum: 512, maximum: 3840, description: 'Chỉ gửi khi người dùng yêu cầu rõ kích thước pixel tùy chỉnh. Cần có height và bỏ qua aspectRatio. MiniMax tối đa 2048.' },
        height: { type: 'integer', minimum: 512, maximum: 3840, description: 'Chỉ gửi khi người dùng yêu cầu rõ kích thước pixel tùy chỉnh. Cần có width và bỏ qua aspectRatio. MiniMax tối đa 2048.' },
        quality: { type: 'string', enum: ['low', 'medium', 'high', 'auto'], description: 'Chỉ dành cho gpt-image-2; mặc định là high.' },
        referenceAssetIds: { type: 'array', items: { type: 'string' }, maxItems: 16, description: 'ID tư liệu ảnh trong dự án. Giới hạn: GPT 16, Gemini 14, MiniMax 1 tham chiếu chủ thể (MiniMax cần R2 đã cấu hình).' },
        maskAssetId: { type: 'string', description: 'Chỉ dành cho chỉnh sửa bằng gpt-image-2. Mặt nạ ảnh của dự án; pixel trong suốt sẽ được thay thế.' },
        count: { type: 'integer', minimum: 1, maximum: 10, description: 'Số ảnh; mặc định là 1. image-01 tối đa 9.' },
        background: { type: 'string', enum: ['transparent', 'opaque', 'auto'], description: 'Chỉ dành cho gpt-image-2. Nền đầu ra.' },
        moderation: { type: 'string', enum: ['low', 'auto'], description: 'Chỉ dành cho gpt-image-2. Mức nghiêm ngặt của kiểm duyệt.' },
        inputFidelity: { type: 'string', enum: ['low', 'high'], description: 'Chỉ dành cho chỉnh sửa bằng gpt-image-2. Độ trung thực của ảnh tham chiếu.' },
        outputFormat: { type: 'string', enum: ['png', 'jpeg', 'webp'], description: 'Chỉ dành cho gpt-image-2. Mặc định là png.' },
        outputCompression: { type: 'integer', minimum: 0, maximum: 100, description: 'Chỉ dành cho gpt-image-2. Chỉ gửi cùng outputFormat=jpeg hoặc webp; không gửi cho PNG.' },
        seed: { type: 'integer', description: 'Chỉ dành cho MiniMax image-01. Seed ngẫu nhiên có thể tái lập.' },
        promptOptimizer: { type: 'boolean', description: 'Chỉ dành cho MiniMax image-01. prompt_optimizer; mặc định chính thức là false.' },
      },
      required: ['prompt', 'name'],
    },
  },
  {
    name: 'submit_voice',
    description: 'Tạo một tư liệu âm thanh TTS bằng ElevenLabs, Doubao, MiniMax, Inworld, Fish Audio, Speechify, OpenAI, Gemini, Mistral hoặc Cartesia. Chỉ tạo tư liệu trong kho media; không đặt hoặc thay thế mục trên dòng thời gian. Hãy xác nhận provider đã cấu hình và giọng cụ thể của provider; timbreWeights của MiniMax có thể trộn nhiều giọng với voiceId rỗng.',
    input_schema: {
      type: 'object',
      properties: {
        provider: { type: 'string', enum: ['elevenlabs', 'doubao', 'minimax', 'inworld', 'fishaudio', 'speechify', 'openai', 'gemini', 'mistral', 'cartesia'], description: 'Provider bắt buộc phải được chọn rõ. Chỉ dùng provider được liệt kê là đã cấu hình trong capabilities. ID giọng và catalog của các provider không thể dùng thay thế cho nhau.' },
        text: { type: 'string', minLength: 1, description: 'Văn bản cần tổng hợp.' },
        voiceId: { type: 'string', description: 'ID giọng cụ thể theo provider đã được người dùng xác nhận. Bắt buộc trừ trường hợp trộn timbreWeights của MiniMax, khi đó phải để rỗng. Không tự tạo preset hoặc dùng lại ID của provider khác.' },
        modelId: { type: 'string', description: 'Chỉ dành cho ElevenLabs, Inworld, Fish Audio, Speechify, OpenAI, Gemini, Mistral hoặc Cartesia. Bỏ qua để dùng mô hình đã cấu hình.' },
        stability: { type: 'number', minimum: 0, maximum: 1, description: 'Chỉ dành cho ElevenLabs. Mặc định là 0.5.' },
        speed: { type: 'number', minimum: 0.5, maximum: 2, description: 'Chỉ dành cho ElevenLabs (0.7–1.2), MiniMax (0.5–2), OpenAI hoặc Cartesia. Mặc định là 1; hỗ trợ theo provider/mô hình được kiểm tra ở server.' },
        similarityBoost: { type: 'number', minimum: 0, maximum: 1, description: 'ElevenLabs voice_settings.similarity_boost.' },
        style: { type: 'number', minimum: 0, maximum: 1, description: 'ElevenLabs voice_settings.style.' },
        useSpeakerBoost: { type: 'boolean', description: 'Tăng cường giọng người nói của ElevenLabs.' },
        languageCode: { type: 'string', description: 'Chỉ dành cho ElevenLabs hoặc Cartesia. Hỗ trợ theo provider/mô hình được kiểm tra ở server.' },
        seed: { type: 'integer', minimum: 0, maximum: 4294967295, description: 'Seed tái lập kết quả của ElevenLabs.' },
        outputFormat: { type: 'string', description: 'Enum đầu ra chính thức của ElevenLabs (ví dụ mp3_44100_128) hoặc định dạng được provider OpenAI/Gemini/Mistral/Cartesia hỗ trợ.' },
        instructions: { type: 'string', description: 'Chỉ dành cho OpenAI hoặc Gemini. Hướng dẫn đọc bằng ngôn ngữ tự nhiên; chỉ gửi khi được yêu cầu và mô hình đã cấu hình hỗ trợ.' },
        optimizeStreamingLatency: { type: 'integer', minimum: 0, maximum: 4, description: 'Mức tối ưu độ trễ streaming của ElevenLabs.' },
        enableLogging: { type: 'boolean', description: 'Điều khiển ghi log request của ElevenLabs.' },
        applyTextNormalization: { type: 'string', enum: ['auto', 'on', 'off'], description: 'Chuẩn hóa văn bản của ElevenLabs.' },
        applyLanguageTextNormalization: { type: 'boolean', description: 'Chuẩn hóa văn bản theo ngôn ngữ của ElevenLabs.' },
        pronunciationDictionaryLocators: { type: 'array', maxItems: 3, items: { type: 'object', properties: { pronunciationDictionaryId: { type: 'string' }, versionId: { type: 'string' } }, required: ['pronunciationDictionaryId', 'versionId'] }, description: 'ElevenLabs dictionary/version locators.' },
        previousText: { type: 'string', description: 'ElevenLabs continuity context before this text.' },
        nextText: { type: 'string', description: 'ElevenLabs continuity context after this text.' },
        previousRequestIds: { type: 'array', items: { type: 'string' }, description: 'ElevenLabs prior request IDs for continuity.' },
        nextRequestIds: { type: 'array', items: { type: 'string' }, description: 'ElevenLabs next request IDs for continuity.' },
        speedRatio: { type: 'number', minimum: 0.5, maximum: 2, description: 'Doubao only. Defaults to 1.' },
        emotion: { type: 'string', description: 'Doubao or MiniMax emotion label. MiniMax accepts: happy, sad, angry, fearful, disgusted, surprised, calm, fluent, whisper.' }, // minimax: shared with doubao
        emotionScale: { type: 'number', minimum: 1, maximum: 5, description: 'Doubao only. Requires emotion.' },
        loudnessRatio: { type: 'number', minimum: 0.5, maximum: 2, description: 'Doubao only. Defaults to 1.' },
        pitch: { type: 'number', minimum: -12, maximum: 12, description: 'Doubao: post-process semitones. MiniMax: native voice_setting.pitch (-12–12).' },
        volume: { type: 'number', exclusiveMinimum: 0, maximum: 10, description: 'MiniMax only. voice_setting.vol (>0–10). Defaults to 1.' },
        performancePrompt: { type: 'string', maxLength: 200, description: 'Doubao only. Natural-language performance direction.' },
        explicitDialect: { type: 'string', enum: ['dongbei', 'shaanxi', 'sichuan'], description: 'Doubao only; supported by the Vivi preset.' },
        // ponytail: Numeric enum will be rejected by Gemini native API (Schema.enum only accepts TYPE_STRING) - write in
        // description, the provider API side will still verify illegal values.
        sampleRate: { type: 'integer', description: 'MiniMax audio_setting.sample_rate. One of 8000/16000/22050/24000/32000/44100.' },
        bitrate: { type: 'integer', description: 'MiniMax MP3 bitrate. One of 32000/64000/128000/256000.' },
        audioFormat: { type: 'string', enum: ['mp3', 'pcm', 'flac', 'wav', 'pcmu_raw', 'pcmu_wav', 'opus'], description: 'MiniMax audio output format.' },
        channel: { type: 'integer', minimum: 1, maximum: 2, description: 'MiniMax output channels (1 = mono, 2 = stereo).' },
        forceCbr: { type: 'boolean', description: 'MiniMax constant bitrate; true requires stream=true and MP3.' },
        stream: { type: 'boolean', description: 'MiniMax HTTP streaming transport. OpenChatCut consumes it server-side and saves one durable audio asset.' },
        excludeAggregatedAudio: { type: 'boolean', description: 'MiniMax stream option. Requires stream=true; concatenates incremental chunks.' },
        languageBoost: { type: 'string', enum: [...MINIMAX_LANGUAGE_BOOSTS], description: 'MiniMax official language_boost enum.' },
        textNormalization: { type: 'boolean', description: 'MiniMax text_normalization.' },
        latexRead: { type: 'boolean', description: 'MiniMax latex_read.' },
        pronunciations: { type: 'array', items: { type: 'string' }, description: 'MiniMax pronunciation_dict.tone entries.' },
        timbreWeights: { type: 'array', minItems: 1, maxItems: 4, items: { type: 'object', properties: { voiceId: { type: 'string' }, weight: { type: 'integer', minimum: 1, maximum: 100 } }, required: ['voiceId', 'weight'] }, description: 'MiniMax multi-voice timbre mix.' },
        voiceModify: { type: 'object', properties: { pitch: { type: 'number', minimum: -100, maximum: 100 }, intensity: { type: 'number', minimum: -100, maximum: 100 }, timbre: { type: 'number', minimum: -100, maximum: 100 }, effect: { type: 'string', enum: ['spacious_echo', 'auditorium_echo', 'lofi_telephone', 'robotic'] } }, description: 'MiniMax voice_modify controls.' },
        subtitleEnable: { type: 'boolean', description: 'MiniMax subtitle generation flag; the JSON response is downloaded as a durable sidecar.' },
        subtitleType: { type: 'string', enum: ['sentence', 'word', 'word_streaming'], description: 'MiniMax subtitle granularity. Requires subtitleEnable; word_streaming also requires stream.' },
        name: { type: 'string', description: 'Optional media-pool asset name.' },
      },
      required: ['provider', 'text'],
    },
  },
  {
    name: 'submit_sound',
    description: 'Generate one sound-effect audio asset in the media pool: ElevenLabs synthesizes synchronously from a text prompt; Sonilo submits an asynchronous SFX job from a project video asset (the rendered cut, up to 3 minutes) with no prompt. Sonilo returns a jobId for track_progress. Does not place timeline items. For ordinary whooshes, clicks, impacts, dings, and similar editing sounds, use the existing library first.',
    input_schema: {
      type: 'object',
      properties: {
        provider: { type: 'string', enum: ['elevenlabs', 'sonilo'], description: 'Defaults to elevenlabs (text prompt). sonilo generates video-matched SFX from sourceAssetId instead of a prompt.' },
        prompt: { type: 'string', description: 'Detailed sound description. Required for elevenlabs; not used by sonilo.' },
        durationSeconds: { type: 'number', minimum: 0.5, maximum: 30, description: 'ElevenLabs only. Optional 0.5–30 seconds; omit to let ElevenLabs choose the duration.' },
        promptInfluence: { type: 'number', minimum: 0, maximum: 1, description: 'ElevenLabs only. Prompt adherence; defaults to 0.3.' },
        loop: { type: 'boolean', description: 'ElevenLabs only. Create a seamless loop; requires the configured eleven_text_to_sound_v2 model.' },
        outputFormat: { type: 'string', description: 'ElevenLabs only. Official codec_sample-rate_bitrate enum, e.g. mp3_44100_128, opus_48000_128, pcm_44100.' },
        sourceAssetId: { type: 'string', description: 'Sonilo only. Project video asset (the rendered cut, ≤3 minutes) the SFX are generated from.' },
        name: { type: 'string', description: 'Optional media-pool asset name.' },
      },
    },
  },
  {
    name: 'submit_music',
    description: 'Submit a Mureka, MiniMax, Atlas Cloud, or Sonilo music job. Mureka supports instrumental, lyrics song, prompt song, soundtrack, and track/stem modes with up to 3 results. MiniMax supports text-to-music and cover. Atlas Cloud supports text-to-music through its asynchronous audio API. Sonilo v2m generates music from a project video asset (the rendered cut, up to 6 minutes) — video-conditioned, with a single optional style prompt. Results are saved to the media pool.',
    input_schema: {
      type: 'object',
      properties: {
        prompt: { type: 'string', maxLength: 2000, description: 'Style/control prompt. Required for most modes; optional with Mureka provider IDs and Sonilo v2m (≤500, works promptless). Mureka max is 1024 or 2000 by mode; MiniMax cover requires 10–300.' },
        provider: { type: 'string', enum: ['mureka', 'minimax', 'atlas', 'sonilo'], description: 'Defaults to mureka.' },
        mode: { type: 'string', enum: ['instrumental', 'song', 'prompt-song', 'soundtrack', 'track', 't2m', 'cover', 'v2m'], description: 'Mureka: instrumental/song/prompt-song/soundtrack/track. MiniMax: t2m/cover. Atlas Cloud: t2m. Sonilo: v2m (video-to-music).' },
        lyrics: { type: 'string', maxLength: 5000, description: 'Mureka song/track or MiniMax t2m/cover lyrics. Provider-specific limits are validated.' },
        isInstrumental: { type: 'boolean', description: 'MiniMax or Atlas Cloud t2m only. Force instrumental.' },
        lyricsOptimizer: { type: 'boolean', description: 'MiniMax t2m only. Auto-generate lyrics from prompt.' },
        sampleRate: { type: 'integer', description: 'MiniMax or Atlas Cloud only. One of 16000/24000/32000/44100; default 44100.' },
        bitrate: { type: 'integer', description: 'MiniMax or Atlas Cloud only. One of 32000/64000/128000/256000; default 256000.' },
        audioFormat: { type: 'string', enum: ['mp3', 'wav', 'pcm', 'flac'], description: 'MiniMax/Atlas Cloud: mp3/wav/pcm. Mureka: mp3/wav/flac. Default mp3.' },
        referenceAssetId: { type: 'string', description: 'MiniMax cover only. Project audio asset id; mutually exclusive with coverFeatureId.' },
        coverFeatureId: { type: 'string', description: 'MiniMax cover only. Preprocessed feature ID; requires lyrics and excludes referenceAssetId.' },
        count: { type: 'integer', minimum: 1, maximum: 3, description: 'Mureka only. Result count; defaults to 1 (official API default is 2).' },
        stream: { type: 'boolean', description: 'Mureka only. Enable provider streaming phase; OpenChatCut still saves durable final files.' },
        styles: { type: 'array', items: { type: 'string', enum: ['pop', 'rock', 'jazz', 'r&b', 'edm', 'ambient', 'folk', 'latin', 'k-pop', 'j-pop', 'house', 'gospel', 'lo-fi'] }, description: 'Mureka prompt-song styles.' },
        gender: { type: 'string', enum: ['female', 'male'], description: 'Mureka lyrics-song preferred vocal gender.' },
        referenceId: { type: 'string', description: 'Mureka song/prompt-song reference ID.' },
        instrumentalId: { type: 'string', description: 'Mureka instrumental file ID; use instead of prompt.' },
        vocalId: { type: 'string', description: 'Mureka cloned vocal ID.' },
        melodyId: { type: 'string', description: 'Mureka lyrics-song melody ID; cannot combine with other controls.' },
        sourceAssetId: { type: 'string', description: 'Mureka soundtrack image/video asset, track-mode audio asset, or Sonilo v2m video asset (the rendered cut, ≤6 minutes).' },
        audioStartMs: { type: 'integer', minimum: 0, description: 'Mureka soundtrack segment start in ms.' },
        audioEndMs: { type: 'integer', minimum: 0, description: 'Mureka soundtrack segment end in ms; range must be at least 3000ms.' },
        songId: { type: 'string', description: 'Mureka track source song ID; excludes sourceAssetId.' },
        trackType: { type: 'string', enum: ['Vocals', 'Instrumental', 'Drums', 'Bass', 'Guitar', 'Keyboard', 'Percussion', 'Strings', 'Synth', 'FX', 'Brass', 'Woodwinds'], description: 'Mureka track/stem type.' },
        generateStartMs: { type: 'integer', minimum: 0, description: 'Mureka track source segment start in ms.' },
        generateEndMs: { type: 'integer', minimum: 0, description: 'Mureka track source segment end in ms.' },
        vocalGender: { type: 'string', enum: ['female', 'male'], description: 'Mureka Vocals track only.' },
        name: { type: 'string', description: 'Optional media-pool asset name.' },
      },
    },
  },
  {
    name: 'submit_video',
    description: 'Submit a Fal catalog, Seedance 2.0, Kling, MiniMax Hailuo, BytePlus Seedance, xAI Grok Imagine, or OFox video generation job and create one video asset in the project media pool. Does not place the video on the timeline. Keep image, video, and audio references in their matching arrays.',
    input_schema: {
      type: 'object',
      properties: {
        model: { type: 'string', enum: ['seedance2', 'kling', 'hailuo', 'byteplus', 'grok-imagine-video', 'ofox', 'fal'], description: 'hailuo is MiniMax: 6 or 10s; firstFrame optional; lastFrame allowed with firstFrame; no multi-ref or multi-shot. 1080p is 6s only. byteplus is BytePlus ModelArk Seedance — same request shape/limits as seedance2. grok-imagine-video is xAI Grok Imagine: text-to-video only, 1–15s, audio track included, no references/frames. ofox is the OFox multi-model gateway (Seedance/Wan and more behind one key): 2–30s with per-model limits enforced by the API; supports firstFrame (and optional lastFrame), or up to 9 refImages (frames and refImages are mutually exclusive); no refVideos/refAudios yet.' }, // minimax: hailuo enum
        falModel: { type: 'string', enum: FAL_VIDEO_MODELS.map((model) => model.id), description: `With model=fal, select a curated Fal video model; omitted uses the saved Fal video default. ${FAL_VIDEO_MODELS.map((model) => `${model.id}: ${falModelSummary(model)}`).join('; ')}. Omit duration/resolution to use model defaults.` },
        prompt: { type: 'string', description: 'Required for normal generation and Kling intelligence; omit for Kling customize.' },
        name: { type: 'string' },
        durationSeconds: { anyOf: [{ type: 'number' }, { type: 'string' }], description: 'For Fal, see falModel limits and omit to use model default. Native providers: integer seconds, 2–15 for Seedance, 3–15 for Kling, exactly 6 or 10 for Hailuo (Hailuo 1080p → 6 only), 1–15 for grok-imagine-video, 2–30 for ofox (per-model limits enforced by the API).' }, // minimax: hailuo durations
        ratio: { type: 'string', description: 'Seedance: 16:9, 4:3, 1:1, 3:4, 9:16, 21:9, adaptive. Kling: 16:9, 9:16, 1:1. grok-imagine-video: 16:9, 9:16, 1:1, 4:3, 3:4, 3:2, 2:3. ofox: 16:9, 9:16, 1:1, 4:3, 3:4, 3:2, 2:3, 21:9, 9:21. Do not send for hailuo.' },
        resolution: { type: 'string', enum: [...new Set(['480p', '512p', '720p', '1080p', '4k', ...FAL_VIDEO_MODELS.flatMap((model) => model.constraints.resolutions)])], description: 'Seedance: 480p/720p(default)/1080p/4k. Hailuo: 512p (Hailuo-02), 720p→API 768P, 1080p (6s only). Kling: pair with mode std/pro. grok-imagine-video: 480p(default)/720p/1080p. ofox: 480p/720p(default)/1080p, per-model support enforced by the API.' },
        mode: { type: 'string', enum: ['std', 'pro'], description: 'Kling only; std=720p, pro=1080p.' },
        firstFrame: { type: 'string', description: 'Project image asset ID, asset:// ID, short unique ID prefix, or same-project asset path.' },
        lastFrame: { type: 'string', description: 'Project image asset reference; requires firstFrame. Supported on seedance2, kling, hailuo, and ofox (not with multi-ref on seedance2/ofox).' },
        refImages: { type: 'array', items: { type: 'string' } },
        refVideos: { type: 'array', items: { type: 'string' } },
        refAudios: { type: 'array', items: { type: 'string' } },
        refVideoMode: { type: 'string', enum: ['feature', 'base'], description: 'Kling only with refVideos. feature (default)=motion/camera/style guide; base=edit that source clip (keep_original_sound).' },
        promptOptimizer: { type: 'boolean', description: 'Hailuo only. MiniMax prompt_optimizer; default true. Set false for more literal prompts.' },
        fastPretreatment: { type: 'boolean', description: 'Hailuo only. MiniMax fast_pretreatment when promptOptimizer is true; default false.' },
        generateAudio: { type: 'boolean', description: 'Seedance/BytePlus/OFox. Generate synchronized audio; default true for models that support audio.' },
        seed: { type: 'integer', description: 'Seedance/BytePlus/OFox. Random seed; determinism depends on the model.' },
        cameraFixed: { type: 'boolean', description: 'Seedance/BytePlus only. Lock camera motion; default false.' },
        watermark: { type: 'boolean', description: 'Seedance/BytePlus only. Add provider watermark; default false.' },
        returnLastFrame: { type: 'boolean', description: 'Seedance/BytePlus only. Save the returned last frame as an additional image asset.' },
        executionExpiresAfter: { type: 'integer', minimum: 3600, maximum: 259200, description: 'Seedance/BytePlus only. Task expiry in seconds.' },
        priority: { type: 'integer', minimum: 0, maximum: 9, description: 'Seedance/BytePlus only. Queue priority.' },
        multiPrompts: {
          type: 'array', minItems: 2, maxItems: 6,
          items: { type: 'object', properties: { prompt: { type: 'string' }, duration: { anyOf: [{ type: 'number' }, { type: 'string' }] }, index: { type: 'integer', minimum: 1 } }, required: ['prompt', 'duration', 'index'] },
          description: 'Kling customize storyboard; indexes start at 1 and durations sum to durationSeconds.',
        },
        shotType: { type: 'string', enum: ['customize', 'intelligence'], description: 'Kling multi-shot mode.' },
      },
      required: ['model'],
    },
  },
  {
    name: 'track_progress',
    description: 'Inspect or wait for asynchronous generation jobs returned by Sonilo submit_sound, submit_music, and submit_video. Successful results are added to the project media pool exactly once.',
    input_schema: {
      type: 'object',
      properties: {
        action: { type: 'string', enum: ['params', 'status', 'wait', 'resume'], description: 'params returns settings, status checks immediately, wait polls, and resume retries only a failed result download without regenerating.' },
        target: { type: 'string', enum: ['generation'] },
        jobIds: { type: 'string', minLength: 1, description: 'One or more comma-separated generation job IDs.' },
        assetIds: { type: 'string', description: 'Reserved; generation jobs are tracked by jobIds.' },
        timeoutSeconds: { type: 'number', minimum: 0, maximum: 3600, description: 'wait timeout; defaults to 90 seconds.' },
      },
      required: ['action', 'target', 'jobIds'],
    },
  },
  {
    name: 'rerun_generation',
    description: 'Explicitly rerun one previously tracked generation operation with its complete original submit args. Exact operation/job IDs win; a prefix is accepted only when unique. Legacy summary-only rows and ambiguous prefixes are rejected before any provider call.',
    input_schema: {
      type: 'object',
      properties: {
        jobId: { type: 'string', minLength: 1, description: 'Exact operation/job ID or a unique prefix. Ambiguous prefixes are rejected with distinguishable candidate IDs.' },
      },
      required: ['jobId'],
    },
  },
  {
    name: 'submit_export',
    description: [
      'Export the active timeline synchronously as MP4/WebM video, MP3/WAV audio, SRT/TXT subtitles,',
      'or an FCPXML project (format=xml) for Premiere / Resolve / FCP.',
      'When MG/captions reference fonts the renderer cannot load, the first call returns unsupportedFonts',
      '— relay to the user and retry with confirmFontFallback=true only after they accept.',
      'For XML, pass nleFormat=fcp_xml (default, Premiere) or fcp_xml_resolve (DaVinci Resolve).',
      'Optional frame boundaries use a half-open [startFrame, endFrameExclusive) range.',
    ].join(' '),
    input_schema: {
      type: 'object',
      properties: {
        format: { type: 'string', enum: ['video', 'audio', 'subtitles', 'xml'] },
        codec: { type: 'string', enum: ['h264', 'vp8', 'mp3', 'wav'], description: 'Video: h264 (default) or vp8. Audio: mp3 (default) or wav.' },
        subtitleFormat: { type: 'string', enum: ['srt', 'txt'], description: 'Defaults to srt.' },
        captionTrackId: { type: 'string', description: 'For subtitle export: C1/C2 alias or stable caption track id. Defaults to C1.' },
        nleFormat: {
          type: 'string',
          enum: ['fcp_xml', 'fcp_xml_resolve'],
          description: 'NLE XML format for format=xml. Defaults to fcp_xml (Premiere). Use fcp_xml_resolve for DaVinci Resolve.',
        },
        name: { type: 'string', description: 'Download filename.' },
        fps: {
          type: 'number',
          description: 'Video output fps: 24|25|30|50|60. Omit to match timeline. Frame counts stay; real duration scales.',
        },
        resolution: {
          type: 'string',
          enum: ['480p', '720p', '1080p'],
          description: 'Video max-height ladder (default timeline size). Scales width to keep aspect.',
        },
        videoBitrate: {
          type: 'integer',
          minimum: 1_000_000,
          maximum: 80_000_000,
          description: 'Video only. Exact output bitrate in bits per second; omit for the renderer default.',
        },
        timelineId: {
          type: 'string',
          description: 'Export a non-active timeline by id/prefix without switching (video/audio/xml).',
        },
        startFrame: { type: 'integer', minimum: 0 },
        endFrameExclusive: { type: 'integer', minimum: 1 },
        startSeconds: { type: 'number', minimum: 0, description: 'Legacy; prefer startFrame.' },
        endSeconds: { type: 'number', minimum: 0, description: 'Legacy; prefer endFrameExclusive.' },
        confirmFontFallback: {
          type: 'boolean',
          description: 'Required true when export would burn unsupported fonts. First call without it returns the unsupported list.',
        },
        motionGraphicRenderKeys: {
          type: 'array',
          items: { type: 'string' },
          description: 'Advanced XML export: render keys returned by export_motion_graphic_prores with filenameMode=xml. Matching MG clips become media references; other MG clips stay placeholders.',
        },
      },
    },
  },
];

export const GENERATE_TOOL_NAMES = new Set(GENERATE_TOOL_SCHEMAS.map((tool) => tool.name));
