import { FAL_IMAGE_MODELS, FAL_VIDEO_MODELS, falModelSummary } from '../../../shared/fal-models';
import type { AgentToolSchema } from '../tool-schema';
import { MINIMAX_LANGUAGE_BOOSTS } from '../../../shared/media-provider-params';

/** Anthropic schema for generating class tools. Just push into this array (it will automatically enter the model's visible tool list). */
export const GENERATE_TOOL_SCHEMAS: AgentToolSchema[] = [
  {
    name: 'submit_image',
    description: 'Tạo một hoặc nhiều ảnh AI (catalog Fal, gpt-image-2, nano-banana, MiniMax image-01, WaveSpeed, BytePlus Seedream hoặc xAI Grok Imagine), lưu vào kho media của dự án và tùy chọn đề xuất thêm vào dòng thời gian hiện tại. Chỉ gọi khi người dùng yêu cầu tạo ảnh rõ ràng.',
    input_schema: {
      type: 'object',
      properties: {
        model: { type: 'string', enum: ['gpt-image-2', 'nano-banana', 'image-01', 'wavespeed', 'byteplus', 'grok-imagine', 'fal'], description: 'gpt-image-2 là mặc định; nano-banana phù hợp khi dùng nhiều ảnh tham chiếu; image-01 là MiniMax (tối đa 9 kết quả; một tham chiếu chủ thể khi đã cấu hình R2); wavespeed là WaveSpeed AI (mô hình ảnh tổng quát nhanh, không có tham chiếu); byteplus là BytePlus ModelArk Seedream (chưa hỗ trợ tham chiếu); grok-imagine là xAI Grok Imagine (chỉ text-to-image, không tham chiếu, tối đa 4 kết quả, 1K/2K).' },
        falModel: { type: 'string', enum: FAL_IMAGE_MODELS.map((model) => model.id), description: `Với model=fal, chọn một mô hình ảnh Fal trong catalog; bỏ qua sẽ dùng mặc định Fal đã lưu. ${FAL_IMAGE_MODELS.map((model) => `${model.id}: ${falModelSummary(model)}`).join('; ')}. Giới hạn riêng của từng mô hình được kiểm tra trước khi gửi.` },
        prompt: { type: 'string', description: 'Mô tả chi tiết ảnh cần tạo.' },
        name: { type: 'string', description: 'Tên mô tả ngắn của tư liệu hiển thị trong kho media.' },
        addToTimeline: { type: 'boolean', description: 'Mặc định là true. Đặt false khi người dùng muốn chỉ giữ kết quả trong kho media/thư viện hoặc yêu cầu không sửa dòng thời gian.' },
        aspectRatio: { type: 'string', enum: [...new Set(['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3', '4:5', '5:4', '21:9', ...FAL_IMAGE_MODELS.flatMap((model) => model.constraints.aspectRatios)])], description: 'Provider gốc mặc định 16:9; Fal dùng mặc định của mô hình được chọn. Tỷ lệ riêng của Fal cần mô hình hỗ trợ. Không gửi width/height cùng aspectRatio.' },
        imageSize: { type: 'string', enum: [...new Set(['512px', '1K', '2K', '4K', ...FAL_IMAGE_MODELS.flatMap((model) => model.constraints.resolutions)])], description: 'Provider gốc mặc định 1K; Fal dùng mặc định của mô hình và kiểm tra kích thước được hỗ trợ. Với Fal, 512px là bí danh của 0.5K. Chỉ dùng 2K/4K khi được yêu cầu rõ ràng. Bị bỏ qua khi đặt width/height tùy chỉnh.' },
        width: { type: 'integer', minimum: 512, maximum: 3840, description: 'Chỉ gửi khi người dùng yêu cầu rõ kích thước pixel tùy chỉnh. Cần có height và bỏ qua aspectRatio. MiniMax tối đa 2048.' },
        height: { type: 'integer', minimum: 512, maximum: 3840, description: 'Chỉ gửi khi người dùng yêu cầu rõ kích thước pixel tùy chỉnh. Cần có width và bỏ qua aspectRatio. MiniMax tối đa 2048.' },
        quality: { type: 'string', enum: ['low', 'medium', 'high', 'auto'], description: 'Chỉ dành cho gpt-image-2; mặc định là high.' },
        referenceAssetIds: { type: 'array', items: { type: 'string' }, maxItems: 16, description: 'ID tư liệu ảnh trong dự án. Giới hạn: GPT 16, Gemini 14, MiniMax 1 tham chiếu chủ thể (MiniMax cần R2 đã cấu hình).' },
        maskAssetId: { type: 'string', description: 'Chỉ dành cho chỉnh sửa bằng gpt-image-2. Mặt nạ ảnh của dự án; pixel trong suốt sẽ được thay thế.' },
        count: { type: 'integer', minimum: 1, maximum: 10, description: 'Số ảnh; mặc định là 1. image-01 tối đa 9.' },
        background: { type: 'string', enum: ['transparent', 'opaque', 'auto'], description: 'Chỉ dành cho gpt-image-2. Nền đầu ra.' },
        moderation: { type: 'string', enum: ['low', 'auto'], description: 'Chỉ dành cho gpt-image-2. Mức nghiêm ngặt của kiểm duyệt.' },
        inputFidelity: { type: 'string', enum: ['low', 'high'], description: 'Chỉ dành cho chỉnh sửa bằng gpt-image-2. Độ trung thực của ảnh tham chiếu.' },
        outputFormat: { type: 'string', enum: ['png', 'jpeg', 'webp'], description: 'Chỉ dành cho gpt-image-2. Mặc định là png.' },
        outputCompression: { type: 'integer', minimum: 0, maximum: 100, description: 'Chỉ dành cho gpt-image-2. Chỉ gửi cùng outputFormat=jpeg hoặc webp; không gửi cho PNG.' },
        seed: { type: 'integer', description: 'Chỉ dành cho MiniMax image-01. Seed ngẫu nhiên có thể tái lập.' },
        promptOptimizer: { type: 'boolean', description: 'Chỉ dành cho MiniMax image-01. prompt_optimizer; mặc định chính thức là false.' },
      },
      required: ['prompt', 'name'],
    },
  },
  {
    name: 'submit_voice',
    description: 'Tạo một tư liệu âm thanh TTS bằng ElevenLabs, Doubao, MiniMax, Inworld, Fish Audio, Speechify, OpenAI, Gemini, Mistral hoặc Cartesia. Chỉ tạo tư liệu trong kho media; không đặt hoặc thay thế mục trên dòng thời gian. Hãy xác nhận provider đã cấu hình và giọng cụ thể của provider; timbreWeights của MiniMax có thể trộn nhiều giọng với voiceId rỗng.',
    input_schema: {
      type: 'object',
      properties: {
        provider: { type: 'string', enum: ['elevenlabs', 'doubao', 'minimax', 'inworld', 'fishaudio', 'speechify', 'openai', 'gemini', 'mistral', 'cartesia'], description: 'Provider bắt buộc phải được chọn rõ. Chỉ dùng provider được liệt kê là đã cấu hình trong capabilities. ID giọng và catalog của các provider không thể dùng thay thế cho nhau.' },
        text: { type: 'string', minLength: 1, description: 'Văn bản cần tổng hợp.' },
        voiceId: { type: 'string', description: 'ID giọng cụ thể theo provider đã được người dùng xác nhận. Bắt buộc trừ trường hợp trộn timbreWeights của MiniMax, khi đó phải để rỗng. Không tự tạo preset hoặc dùng lại ID của provider khác.' },
        modelId: { type: 'string', description: 'Chỉ dành cho ElevenLabs, Inworld, Fish Audio, Speechify, OpenAI, Gemini, Mistral hoặc Cartesia. Bỏ qua để dùng mô hình đã cấu hình.' },
        stability: { type: 'number', minimum: 0, maximum: 1, description: 'Chỉ dành cho ElevenLabs. Mặc định là 0.5.' },
        speed: { type: 'number', minimum: 0.5, maximum: 2, description: 'Chỉ dành cho ElevenLabs (0.7–1.2), MiniMax (0.5–2), OpenAI hoặc Cartesia. Mặc định là 1; hỗ trợ theo provider/mô hình được kiểm tra ở server.' },
        similarityBoost: { type: 'number', minimum: 0, maximum: 1, description: 'voice_settings.similarity_boost của ElevenLabs.' },
        style: { type: 'number', minimum: 0, maximum: 1, description: 'voice_settings.style của ElevenLabs.' },
        useSpeakerBoost: { type: 'boolean', description: 'Tăng cường giọng người nói của ElevenLabs.' },
        languageCode: { type: 'string', description: 'Chỉ dành cho ElevenLabs hoặc Cartesia. Hỗ trợ theo provider/mô hình được kiểm tra ở server.' },
        seed: { type: 'integer', minimum: 0, maximum: 4294967295, description: 'Seed tái lập kết quả của ElevenLabs.' },
        outputFormat: { type: 'string', description: 'Enum đầu ra chính thức của ElevenLabs (ví dụ mp3_44100_128) hoặc định dạng được provider OpenAI/Gemini/Mistral/Cartesia hỗ trợ.' },
        instructions: { type: 'string', description: 'Chỉ dành cho OpenAI hoặc Gemini. Hướng dẫn đọc bằng ngôn ngữ tự nhiên; chỉ gửi khi được yêu cầu và mô hình đã cấu hình hỗ trợ.' },
        optimizeStreamingLatency: { type: 'integer', minimum: 0, maximum: 4, description: 'Mức tối ưu độ trễ streaming của ElevenLabs.' },
        enableLogging: { type: 'boolean', description: 'Điều khiển ghi log request của ElevenLabs.' },
        applyTextNormalization: { type: 'string', enum: ['auto', 'on', 'off'], description: 'Chuẩn hóa văn bản của ElevenLabs.' },
        applyLanguageTextNormalization: { type: 'boolean', description: 'Chuẩn hóa văn bản theo ngôn ngữ của ElevenLabs.' },
        pronunciationDictionaryLocators: { type: 'array', maxItems: 3, items: { type: 'object', properties: { pronunciationDictionaryId: { type: 'string' }, versionId: { type: 'string' } }, required: ['pronunciationDictionaryId', 'versionId'] }, description: 'Bộ định vị từ điển phát âm/phiên bản của ElevenLabs.' },
        previousText: { type: 'string', description: 'Ngữ cảnh liên tục của ElevenLabs trước đoạn văn này.' },
        nextText: { type: 'string', description: 'Ngữ cảnh liên tục của ElevenLabs sau đoạn văn này.' },
        previousRequestIds: { type: 'array', items: { type: 'string' }, description: 'ID request trước đó của ElevenLabs để duy trì mạch đọc.' },
        nextRequestIds: { type: 'array', items: { type: 'string' }, description: 'ID request tiếp theo của ElevenLabs để duy trì mạch đọc.' },
        speedRatio: { type: 'number', minimum: 0.5, maximum: 2, description: 'Chỉ dành cho Doubao. Mặc định là 1.' },
        emotion: { type: 'string', description: 'Nhãn cảm xúc của Doubao hoặc MiniMax. MiniMax chấp nhận: happy, sad, angry, fearful, disgusted, surprised, calm, fluent, whisper.' }, // minimax: shared with doubao
        emotionScale: { type: 'number', minimum: 1, maximum: 5, description: 'Chỉ dành cho Doubao. Cần có emotion.' },
        loudnessRatio: { type: 'number', minimum: 0.5, maximum: 2, description: 'Chỉ dành cho Doubao. Mặc định là 1.' },
        pitch: { type: 'number', minimum: -12, maximum: 12, description: 'Doubao: bán âm sau xử lý. MiniMax: voice_setting.pitch gốc (-12–12).' },
        volume: { type: 'number', exclusiveMinimum: 0, maximum: 10, description: 'Chỉ dành cho MiniMax. voice_setting.vol (>0–10). Mặc định là 1.' },
        performancePrompt: { type: 'string', maxLength: 200, description: 'Chỉ dành cho Doubao. Hướng dẫn thể hiện bằng ngôn ngữ tự nhiên.' },
        explicitDialect: { type: 'string', enum: ['dongbei', 'shaanxi', 'sichuan'], description: 'Chỉ dành cho Doubao; preset Vivi hỗ trợ trường này.' },
        // ponytail: Numeric enum will be rejected by Gemini native API (Schema.enum only accepts TYPE_STRING) - write in
        // description, the provider API side will still verify illegal values.
        sampleRate: { type: 'integer', description: 'audio_setting.sample_rate của MiniMax. Một trong 8000/16000/22050/24000/32000/44100.' },
        bitrate: { type: 'integer', description: 'Bitrate MP3 của MiniMax. Một trong 32000/64000/128000/256000.' },
        audioFormat: { type: 'string', enum: ['mp3', 'pcm', 'flac', 'wav', 'pcmu_raw', 'pcmu_wav', 'opus'], description: 'Định dạng âm thanh đầu ra của MiniMax.' },
        channel: { type: 'integer', minimum: 1, maximum: 2, description: 'Số kênh đầu ra MiniMax (1 = mono, 2 = stereo).' },
        forceCbr: { type: 'boolean', description: 'Bitrate cố định của MiniMax; true yêu cầu stream=true và MP3.' },
        stream: { type: 'boolean', description: 'Giao thức streaming HTTP của MiniMax. OpenChatCut xử lý ở server và lưu một tư liệu âm thanh bền vững.' },
        excludeAggregatedAudio: { type: 'boolean', description: 'Tùy chọn stream của MiniMax. Cần stream=true; nối các phần tăng dần.' },
        languageBoost: { type: 'string', enum: [...MINIMAX_LANGUAGE_BOOSTS], description: 'Enum language_boost chính thức của MiniMax.' },
        textNormalization: { type: 'boolean', description: 'text_normalization của MiniMax.' },
        latexRead: { type: 'boolean', description: 'latex_read của MiniMax.' },
        pronunciations: { type: 'array', items: { type: 'string' }, description: 'Các mục pronunciation_dict.tone của MiniMax.' },
        timbreWeights: { type: 'array', minItems: 1, maxItems: 4, items: { type: 'object', properties: { voiceId: { type: 'string' }, weight: { type: 'integer', minimum: 1, maximum: 100 } }, required: ['voiceId', 'weight'] }, description: 'Trộn timbre nhiều giọng của MiniMax.' },
        voiceModify: { type: 'object', properties: { pitch: { type: 'number', minimum: -100, maximum: 100 }, intensity: { type: 'number', minimum: -100, maximum: 100 }, timbre: { type: 'number', minimum: -100, maximum: 100 }, effect: { type: 'string', enum: ['spacious_echo', 'auditorium_echo', 'lofi_telephone', 'robotic'] } }, description: 'Các điều khiển voice_modify của MiniMax.' },
        subtitleEnable: { type: 'boolean', description: 'Cờ tạo phụ đề của MiniMax; phản hồi JSON được tải xuống thành sidecar bền vững.' },
        subtitleType: { type: 'string', enum: ['sentence', 'word', 'word_streaming'], description: 'Mức chi tiết phụ đề của MiniMax. Cần subtitleEnable; word_streaming cũng cần stream.' },
        name: { type: 'string', description: 'Tên tư liệu tùy chọn trong kho media.' },
      },
      required: ['provider', 'text'],
    },
  },
  {
    name: 'submit_sound',
    description: 'Tạo một tư liệu âm thanh hiệu ứng trong kho media: ElevenLabs tổng hợp đồng bộ từ prompt văn bản; Sonilo gửi job SFX bất đồng bộ từ tư liệu video của dự án (bản cắt đã kết xuất, tối đa 3 phút) mà không cần prompt. Sonilo trả về jobId để dùng với track_progress. Không đặt mục lên dòng thời gian. Với các âm thanh chỉnh sửa thông thường như tiếng vút, click, va chạm, leng keng và tương tự, hãy ưu tiên dùng thư viện có sẵn.',
    input_schema: {
      type: 'object',
      properties: {
        provider: { type: 'string', enum: ['elevenlabs', 'sonilo'], description: 'Mặc định là elevenlabs (prompt văn bản). sonilo tạo SFX khớp với video từ sourceAssetId thay vì prompt.' },
        prompt: { type: 'string', description: 'Mô tả chi tiết âm thanh. Bắt buộc với elevenlabs; sonilo không dùng.' },
        durationSeconds: { type: 'number', minimum: 0.5, maximum: 30, description: 'Chỉ dành cho ElevenLabs. Tùy chọn 0.5–30 giây; bỏ qua để ElevenLabs tự chọn thời lượng.' },
        promptInfluence: { type: 'number', minimum: 0, maximum: 1, description: 'Chỉ dành cho ElevenLabs. Mức bám theo prompt; mặc định là 0.3.' },
        loop: { type: 'boolean', description: 'Chỉ dành cho ElevenLabs. Tạo vòng lặp liền mạch; cần mô hình eleven_text_to_sound_v2 đã cấu hình.' },
        outputFormat: { type: 'string', description: 'Chỉ dành cho ElevenLabs. Enum codec_sample-rate_bitrate chính thức, ví dụ mp3_44100_128, opus_48000_128, pcm_44100.' },
        sourceAssetId: { type: 'string', description: 'Chỉ dành cho Sonilo. Tư liệu video của dự án (bản cắt đã kết xuất, ≤3 phút) dùng để tạo SFX.' },
        name: { type: 'string', description: 'Tên tư liệu tùy chọn trong kho media.' },
      },
    },
  },
  {
    name: 'submit_music',
    description: 'Gửi job tạo nhạc bằng Mureka, MiniMax, Atlas Cloud hoặc Sonilo. Mureka hỗ trợ các chế độ nhạc không lời, bài hát có lời, bài hát từ prompt, nhạc nền và track/stem với tối đa 3 kết quả. MiniMax hỗ trợ text-to-music và cover. Atlas Cloud hỗ trợ text-to-music qua API âm thanh bất đồng bộ. Sonilo v2m tạo nhạc từ tư liệu video của dự án (bản cắt đã kết xuất, tối đa 6 phút), có điều kiện theo video và một prompt phong cách tùy chọn. Kết quả được lưu vào kho media.',
    input_schema: {
      type: 'object',
      properties: {
        prompt: { type: 'string', maxLength: 2000, description: 'Prompt điều khiển/phong cách. Bắt buộc ở hầu hết chế độ; tùy chọn khi dùng ID provider của Mureka và Sonilo v2m (≤500, có thể bỏ prompt). Mureka giới hạn 1024 hoặc 2000 tùy chế độ; MiniMax cover yêu cầu 10–300.' },
        provider: { type: 'string', enum: ['mureka', 'minimax', 'atlas', 'sonilo'], description: 'Mặc định là mureka.' },
        mode: { type: 'string', enum: ['instrumental', 'song', 'prompt-song', 'soundtrack', 'track', 't2m', 'cover', 'v2m'], description: 'Mureka: instrumental/song/prompt-song/soundtrack/track. MiniMax: t2m/cover. Atlas Cloud: t2m. Sonilo: v2m (video-to-music).' },
        lyrics: { type: 'string', maxLength: 5000, description: 'Lời bài hát Mureka song/track hoặc MiniMax t2m/cover. Giới hạn theo provider được kiểm tra.' },
        isInstrumental: { type: 'boolean', description: 'Chỉ dành cho t2m của MiniMax hoặc Atlas Cloud. Ép tạo nhạc không lời.' },
        lyricsOptimizer: { type: 'boolean', description: 'Chỉ dành cho MiniMax t2m. Tự tạo lời từ prompt.' },
        sampleRate: { type: 'integer', description: 'Chỉ dành cho MiniMax hoặc Atlas Cloud. Một trong 16000/24000/32000/44100; mặc định 44100.' },
        bitrate: { type: 'integer', description: 'Chỉ dành cho MiniMax hoặc Atlas Cloud. Một trong 32000/64000/128000/256000; mặc định 256000.' },
        audioFormat: { type: 'string', enum: ['mp3', 'wav', 'pcm', 'flac'], description: 'MiniMax/Atlas Cloud: mp3/wav/pcm. Mureka: mp3/wav/flac. Mặc định mp3.' },
        referenceAssetId: { type: 'string', description: 'Chỉ dành cho MiniMax cover. ID tư liệu âm thanh của dự án; không dùng đồng thời với coverFeatureId.' },
        coverFeatureId: { type: 'string', description: 'Chỉ dành cho MiniMax cover. ID đặc trưng đã tiền xử lý; cần lyrics và không dùng cùng referenceAssetId.' },
        count: { type: 'integer', minimum: 1, maximum: 3, description: 'Chỉ dành cho Mureka. Số kết quả; mặc định là 1 (mặc định API chính thức là 2).' },
        stream: { type: 'boolean', description: 'Chỉ dành cho Mureka. Bật giai đoạn streaming của provider; OpenChatCut vẫn lưu tệp cuối bền vững.' },
        styles: { type: 'array', items: { type: 'string', enum: ['pop', 'rock', 'jazz', 'r&b', 'edm', 'ambient', 'folk', 'latin', 'k-pop', 'j-pop', 'house', 'gospel', 'lo-fi'] }, description: 'Phong cách prompt-song của Mureka.' },
        gender: { type: 'string', enum: ['female', 'male'], description: 'Giới tính giọng hát ưu tiên cho lyrics-song của Mureka.' },
        referenceId: { type: 'string', description: 'ID tham chiếu song/prompt-song của Mureka.' },
        instrumentalId: { type: 'string', description: 'ID tệp nhạc không lời của Mureka; dùng thay cho prompt.' },
        vocalId: { type: 'string', description: 'ID giọng hát đã clone của Mureka.' },
        melodyId: { type: 'string', description: 'ID giai điệu lyrics-song của Mureka; không thể dùng cùng các điều khiển khác.' },
        sourceAssetId: { type: 'string', description: 'Tư liệu ảnh/video soundtrack của Mureka, tư liệu âm thanh ở chế độ track hoặc tư liệu video v2m của Sonilo (bản cắt đã kết xuất, ≤6 phút).' },
        audioStartMs: { type: 'integer', minimum: 0, description: 'Điểm bắt đầu đoạn soundtrack Mureka tính bằng ms.' },
        audioEndMs: { type: 'integer', minimum: 0, description: 'Điểm kết thúc đoạn soundtrack Mureka tính bằng ms; phạm vi phải ít nhất 3000ms.' },
        songId: { type: 'string', description: 'ID bài hát nguồn của track Mureka; không dùng cùng sourceAssetId.' },
        trackType: { type: 'string', enum: ['Vocals', 'Instrumental', 'Drums', 'Bass', 'Guitar', 'Keyboard', 'Percussion', 'Strings', 'Synth', 'FX', 'Brass', 'Woodwinds'], description: 'Loại track/stem của Mureka.' },
        generateStartMs: { type: 'integer', minimum: 0, description: 'Điểm bắt đầu đoạn nguồn của track Mureka tính bằng ms.' },
        generateEndMs: { type: 'integer', minimum: 0, description: 'Điểm kết thúc đoạn nguồn của track Mureka tính bằng ms.' },
        vocalGender: { type: 'string', enum: ['female', 'male'], description: 'Chỉ dành cho track Vocals của Mureka.' },
        name: { type: 'string', description: 'Tên tư liệu tùy chọn trong kho media.' },
      },
    },
  },
  {
    name: 'submit_video',
    description: 'Gửi job tạo video bằng catalog Fal, Seedance 2.0, Kling, MiniMax Hailuo, BytePlus Seedance, xAI Grok Imagine hoặc OFox và tạo một tư liệu video trong kho media của dự án. Không đặt video lên dòng thời gian. Đặt tham chiếu ảnh, video và âm thanh vào đúng mảng tương ứng.',
    input_schema: {
      type: 'object',
      properties: {
        model: { type: 'string', enum: ['seedance2', 'kling', 'hailuo', 'byteplus', 'grok-imagine-video', 'ofox', 'fal'], description: 'hailuo là MiniMax: 6 hoặc 10 giây; firstFrame tùy chọn; lastFrame được phép khi có firstFrame; không hỗ trợ nhiều tham chiếu hoặc nhiều shot. 1080p chỉ dành cho 6 giây. byteplus là BytePlus ModelArk Seedance — cùng dạng request/giới hạn với seedance2. grok-imagine-video là xAI Grok Imagine: chỉ text-to-video, 1–15 giây, có track âm thanh, không tham chiếu/frame. ofox là gateway đa mô hình OFox (Seedance/Wan và các mô hình khác dùng chung một key): 2–30 giây với giới hạn theo mô hình do API kiểm tra; hỗ trợ firstFrame (và lastFrame tùy chọn), hoặc tối đa 9 refImages (frames và refImages không dùng đồng thời); chưa hỗ trợ refVideos/refAudios.' }, // minimax: hailuo enum
        falModel: { type: 'string', enum: FAL_VIDEO_MODELS.map((model) => model.id), description: `Với model=fal, chọn một mô hình video Fal trong catalog; bỏ qua sẽ dùng mặc định Fal đã lưu. ${FAL_VIDEO_MODELS.map((model) => `${model.id}: ${falModelSummary(model)}`).join('; ')}. Bỏ qua duration/resolution để dùng mặc định của mô hình.` },
        prompt: { type: 'string', description: 'Bắt buộc với tạo thông thường và Kling intelligence; bỏ qua với Kling customize.' },
        name: { type: 'string', description: 'Tên tư liệu tùy chọn trong kho media.' },
        durationSeconds: { anyOf: [{ type: 'number' }, { type: 'string' }], description: 'Với Fal, xem giới hạn falModel và bỏ qua để dùng mặc định mô hình. Provider gốc: số giây nguyên, 2–15 cho Seedance, 3–15 cho Kling, chính xác 6 hoặc 10 cho Hailuo (Hailuo 1080p → chỉ 6), 1–15 cho grok-imagine-video, 2–30 cho ofox (giới hạn theo mô hình do API kiểm tra).' }, // minimax: hailuo durations
        ratio: { type: 'string', description: 'Seedance: 16:9, 4:3, 1:1, 3:4, 9:16, 21:9, adaptive. Kling: 16:9, 9:16, 1:1. grok-imagine-video: 16:9, 9:16, 1:1, 4:3, 3:4, 3:2, 2:3. ofox: 16:9, 9:16, 1:1, 4:3, 3:4, 3:2, 2:3, 21:9, 9:21. Không gửi cho hailuo.' },
        resolution: { type: 'string', enum: [...new Set(['480p', '512p', '720p', '1080p', '4k', ...FAL_VIDEO_MODELS.flatMap((model) => model.constraints.resolutions)])], description: 'Seedance: 480p/720p (mặc định)/1080p/4k. Hailuo: 512p (Hailuo-02), 720p→API 768P, 1080p (chỉ 6 giây). Kling: kết hợp với mode std/pro. grok-imagine-video: 480p (mặc định)/720p/1080p. ofox: 480p/720p (mặc định)/1080p, hỗ trợ theo mô hình do API kiểm tra.' },
        mode: { type: 'string', enum: ['std', 'pro'], description: 'Chỉ dành cho Kling; std=720p, pro=1080p.' },
        firstFrame: { type: 'string', description: 'ID tư liệu ảnh của dự án, ID asset://, tiền tố ID ngắn duy nhất hoặc đường dẫn tư liệu trong cùng dự án.' },
        lastFrame: { type: 'string', description: 'Tham chiếu tư liệu ảnh của dự án; cần firstFrame. Được hỗ trợ trên seedance2, kling, hailuo và ofox (không dùng cùng nhiều tham chiếu trên seedance2/ofox).' },
        refImages: { type: 'array', items: { type: 'string' } },
        refVideos: { type: 'array', items: { type: 'string' } },
        refAudios: { type: 'array', items: { type: 'string' } },
        refVideoMode: { type: 'string', enum: ['feature', 'base'], description: 'Chỉ dành cho Kling cùng refVideos. feature (mặc định)=hướng dẫn chuyển động/camera/phong cách; base=chỉnh sửa đoạn nguồn đó (keep_original_sound).' },
        promptOptimizer: { type: 'boolean', description: 'Chỉ dành cho Hailuo. prompt_optimizer của MiniMax; mặc định true. Đặt false để prompt sát nghĩa hơn.' },
        fastPretreatment: { type: 'boolean', description: 'Chỉ dành cho Hailuo. fast_pretreatment của MiniMax khi promptOptimizer là true; mặc định false.' },
        generateAudio: { type: 'boolean', description: 'Seedance/BytePlus/OFox. Tạo âm thanh đồng bộ; mặc định true với mô hình hỗ trợ âm thanh.' },
        seed: { type: 'integer', description: 'Seedance/BytePlus/OFox. Seed ngẫu nhiên; khả năng tái lập phụ thuộc mô hình.' },
        cameraFixed: { type: 'boolean', description: 'Chỉ dành cho Seedance/BytePlus. Khóa chuyển động camera; mặc định false.' },
        watermark: { type: 'boolean', description: 'Chỉ dành cho Seedance/BytePlus. Thêm watermark của provider; mặc định false.' },
        returnLastFrame: { type: 'boolean', description: 'Chỉ dành cho Seedance/BytePlus. Lưu last frame trả về thành một tư liệu ảnh bổ sung.' },
        executionExpiresAfter: { type: 'integer', minimum: 3600, maximum: 259200, description: 'Chỉ dành cho Seedance/BytePlus. Thời hạn job tính bằng giây.' },
        priority: { type: 'integer', minimum: 0, maximum: 9, description: 'Chỉ dành cho Seedance/BytePlus. Độ ưu tiên trong hàng đợi.' },
        multiPrompts: {
          type: 'array', minItems: 2, maxItems: 6,
          items: { type: 'object', properties: { prompt: { type: 'string' }, duration: { anyOf: [{ type: 'number' }, { type: 'string' }] }, index: { type: 'integer', minimum: 1 } }, required: ['prompt', 'duration', 'index'] },
          description: 'Storyboard Kling customize; index bắt đầu từ 1 và tổng duration bằng durationSeconds.',
        },
        shotType: { type: 'string', enum: ['customize', 'intelligence'], description: 'Chế độ nhiều shot của Kling.' },
      },
      required: ['model'],
    },
  },
  {
    name: 'track_progress',
    description: 'Xem hoặc chờ các job tạo bất đồng bộ do Sonilo submit_sound, submit_music và submit_video trả về. Kết quả thành công được thêm vào kho media của dự án đúng một lần.',
    input_schema: {
      type: 'object',
      properties: {
        action: { type: 'string', enum: ['params', 'status', 'wait', 'resume'], description: 'params trả về thiết lập, status kiểm tra ngay, wait thăm dò trạng thái, còn resume chỉ thử tải lại kết quả thất bại mà không tạo lại.' },
        target: { type: 'string', enum: ['generation'] },
        jobIds: { type: 'string', minLength: 1, description: 'Một hoặc nhiều ID job tạo, phân tách bằng dấu phẩy.' },
        assetIds: { type: 'string', description: 'Dành riêng; job tạo được theo dõi bằng jobIds.' },
        timeoutSeconds: { type: 'number', minimum: 0, maximum: 3600, description: 'Thời gian chờ của wait; mặc định là 90 giây.' },
      },
      required: ['action', 'target', 'jobIds'],
    },
  },
  {
    name: 'rerun_generation',
    description: 'Chạy lại rõ ràng một tác vụ tạo đã theo dõi trước đó bằng đầy đủ tham số submit ban đầu. ID operation/job chính xác được ưu tiên; chỉ chấp nhận tiền tố khi duy nhất. Các dòng cũ chỉ có tóm tắt và tiền tố mơ hồ sẽ bị từ chối trước khi gọi provider.',
    input_schema: {
      type: 'object',
      properties: {
        jobId: { type: 'string', minLength: 1, description: 'ID operation/job chính xác hoặc tiền tố duy nhất. Tiền tố mơ hồ sẽ bị từ chối và trả về các ID ứng viên để phân biệt.' },
      },
      required: ['jobId'],
    },
  },
  {
    name: 'submit_export',
    description: [
      'Xuất dòng thời gian hiện tại đồng bộ thành video MP4/WebM, âm thanh MP3/WAV, phụ đề SRT/TXT,',
      'hoặc dự án FCPXML (format=xml) cho Premiere / Resolve / FCP.',
      'Khi MG/phụ đề tham chiếu font mà bộ kết xuất không tải được, lần gọi đầu sẽ trả về unsupportedFonts',
      '— chuyển thông tin cho người dùng và chỉ thử lại với confirmFontFallback=true sau khi họ chấp nhận.',
      'Với XML, truyền nleFormat=fcp_xml (mặc định, Premiere) hoặc fcp_xml_resolve (DaVinci Resolve).',
      'Giới hạn frame tùy chọn dùng khoảng nửa mở [startFrame, endFrameExclusive).',
    ].join(' '),
    input_schema: {
      type: 'object',
      properties: {
        format: { type: 'string', enum: ['video', 'audio', 'subtitles', 'xml'] },
        codec: { type: 'string', enum: ['h264', 'vp8', 'mp3', 'wav'], description: 'Video: h264 (mặc định) hoặc vp8. Âm thanh: mp3 (mặc định) hoặc wav.' },
        subtitleFormat: { type: 'string', enum: ['srt', 'txt'], description: 'Mặc định là srt.' },
        captionTrackId: { type: 'string', description: 'Khi xuất phụ đề: bí danh C1/C2 hoặc ID track phụ đề ổn định. Mặc định là C1.' },
        nleFormat: {
          type: 'string',
          enum: ['fcp_xml', 'fcp_xml_resolve'],
          description: 'Định dạng NLE XML khi format=xml. Mặc định là fcp_xml (Premiere). Dùng fcp_xml_resolve cho DaVinci Resolve.',
        },
        name: { type: 'string', description: 'Tên tệp tải xuống.' },
        fps: {
          type: 'number',
          description: 'FPS đầu ra video: 24|25|30|50|60. Bỏ qua để khớp dòng thời gian. Số frame giữ nguyên; thời lượng thực thay đổi theo tỷ lệ.',
        },
        resolution: {
          type: 'string',
          enum: ['480p', '720p', '1080p'],
          description: 'Mức chiều cao tối đa của video (mặc định theo kích thước dòng thời gian). Tự scale chiều rộng để giữ tỷ lệ.',
        },
        videoBitrate: {
          type: 'integer',
          minimum: 1_000_000,
          maximum: 80_000_000,
          description: 'Chỉ dành cho video. Bitrate đầu ra chính xác tính bằng bit/giây; bỏ qua để dùng mặc định của bộ kết xuất.',
        },
        timelineId: {
          type: 'string',
          description: 'Xuất dòng thời gian không hoạt động bằng ID/tiền tố mà không chuyển sang dòng đó (video/audio/xml).',
        },
        startFrame: { type: 'integer', minimum: 0 },
        endFrameExclusive: { type: 'integer', minimum: 1 },
        startSeconds: { type: 'number', minimum: 0, description: 'Cũ; ưu tiên dùng startFrame.' },
        endSeconds: { type: 'number', minimum: 0, description: 'Cũ; ưu tiên dùng endFrameExclusive.' },
        confirmFontFallback: {
          type: 'boolean',
          description: 'Bắt buộc là true khi xuất sẽ nhúng font không được hỗ trợ. Lần gọi đầu không có trường này sẽ trả về danh sách font không hỗ trợ.',
        },
        motionGraphicRenderKeys: {
          type: 'array',
          items: { type: 'string' },
          description: 'Xuất XML nâng cao: các khóa render do export_motion_graphic_prores trả về với filenameMode=xml. Đoạn MG tương ứng sẽ trở thành tham chiếu media; các đoạn MG khác giữ dạng placeholder.',
        },
      },
    },
  },
];

export const GENERATE_TOOL_NAMES = new Set(GENERATE_TOOL_SCHEMAS.map((tool) => tool.name));
